default: &default
  encoding: UTF-8
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: yero
  password: yero
  port: 5432

development: &development
  adapter: postgresql
  encoding: unicode
  database: octopus
  pool: 5
  username: liuyang
  password: root
  host: 127.0.0.1

test:
  <<: *development
  database: yero_test