default: &default
  encoding: UTF-8
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: yero
  password: yero
  port: 5432

development:
  <<: *default
  database: yero_development

test:
  <<: *default
  database: yero_test