GMAIL_USERNAME: 'c.tnecniv@gmail.com'
GMAIL_PASSWORD: 'vincentchu1'

S3_BUCKET_NAME: 'whisprdev'
AWS_ACCESS_KEY_ID: 'AKIAJIAYFOO6UEOFT53A'
AWS_SECRET_ACCESS_KEY: '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'
