class CreateTimeZones < ActiveRecord::Migration
  def change
    create_table :time_zones do |t|
    	t.string :timezone
      	t.timestamps
    end

    TimeZone.create(timezone: "Pacific/Midway")
    TimeZone.create(timezone: "Pacific/Pago_Pago")
    TimeZone.create(timezone: "Pacific/Honolulu")

    TimeZone.create(timezone: "America/Juneau")
    TimeZone.create(timezone: "America/Los_Angeles")
    TimeZone.create(timezone: "America/Tijuana")
    TimeZone.create(timezone: "America/Denver")
    TimeZone.create(timezone: "America/Phoenix")
    TimeZone.create(timezone: "America/Chihuahua")
    TimeZone.create(timezone: "America/Mazatlan")
    TimeZone.create(timezone: "America/Chicago")
    TimeZone.create(timezone: "America/Regina")
    TimeZone.create(timezone: "America/Mexico_City")
    TimeZone.create(timezone: "America/Monterrey")
    TimeZone.create(timezone: "America/Guatemala")
    TimeZone.create(timezone: "America/New_York")
    TimeZone.create(timezone: "America/Indiana/Indianapolis")
    TimeZone.create(timezone: "America/Bogota")
    TimeZone.create(timezone: "America/Lima")
    TimeZone.create(timezone: "America/Halifax")
    TimeZone.create(timezone: "America/Caracas")
    TimeZone.create(timezone: "America/La_Paz")
    TimeZone.create(timezone: "America/Santiago")
    TimeZone.create(timezone: "America/St_Johns")
    TimeZone.create(timezone: "America/Sao_Paulo")
    TimeZone.create(timezone: "America/Argentina/Buenos_Aires")
    TimeZone.create(timezone: "America/Montevideo")
    TimeZone.create(timezone: "America/Guyana")

    TimeZone.create(timezone: "Atlantic/South_Georgia")
    TimeZone.create(timezone: "Atlantic/Azores")
    TimeZone.create(timezone: "Atlantic/Cape_Verde")

    TimeZone.create(timezone: "Europe/Athens")
    TimeZone.create(timezone: "Europe/Istanbul")
    TimeZone.create(timezone: "Europe/Dublin")
    TimeZone.create(timezone: "Europe/London")
    TimeZone.create(timezone: "Europe/Lisbon")
    TimeZone.create(timezone: "Europe/Belgrade")
    TimeZone.create(timezone: "Europe/Bratislava")
    TimeZone.create(timezone: "Europe/Bucharest")
    TimeZone.create(timezone: "Europe/Bratislava")
    TimeZone.create(timezone: "Europe/Budapest")
    TimeZone.create(timezone: "Europe/Ljubljana")
    TimeZone.create(timezone: "Europe/Prague")
    TimeZone.create(timezone: "Europe/Sarajevo")
    TimeZone.create(timezone: "Europe/Skopje")
    TimeZone.create(timezone: "Europe/Warsaw")
    TimeZone.create(timezone: "Europe/Zagreb")
    TimeZone.create(timezone: "Europe/Brussels")
    TimeZone.create(timezone: "Europe/Copenhagen")
    TimeZone.create(timezone: "Europe/Madrid")
    TimeZone.create(timezone: "Europe/Helsinki")
    TimeZone.create(timezone: "Europe/Kiev")
    TimeZone.create(timezone: "Europe/Riga")
    TimeZone.create(timezone: "Europe/Sofia")
    TimeZone.create(timezone: "Europe/Tallinn")
    TimeZone.create(timezone: "Europe/Vilnius")
    TimeZone.create(timezone: "Europe/Paris")
    TimeZone.create(timezone: "Europe/Amsterdam")
    TimeZone.create(timezone: "Europe/Berlin")
    TimeZone.create(timezone: "Europe/Rome")
    TimeZone.create(timezone: "Europe/Stockholm")
    TimeZone.create(timezone: "Europe/Vienna")
    TimeZone.create(timezone: "Europe/Budapest")
    TimeZone.create(timezone: "Europe/Minsk")
    TimeZone.create(timezone: "Europe/Ljubljana")
    TimeZone.create(timezone: "Europe/Prague")
    TimeZone.create(timezone: "Europe/Sarajevo")
    TimeZone.create(timezone: "Europe/Skopje")
    TimeZone.create(timezone: "Europe/Warsaw")
    TimeZone.create(timezone: "Europe/Zagreb")
    TimeZone.create(timezone: "Europe/Brussels")
    TimeZone.create(timezone: "Europe/Copenhagen")
    TimeZone.create(timezone: "Europe/Madrid")
    TimeZone.create(timezone: "Europe/Paris")
    TimeZone.create(timezone: "Europe/Amsterdam")
    TimeZone.create(timezone: "Europe/Berlin")
    TimeZone.create(timezone: "Europe/Rome")
    TimeZone.create(timezone: "Europe/Stockholm")
    TimeZone.create(timezone: "Europe/Vienna")
    TimeZone.create(timezone: "Europe/Moscow")

    TimeZone.create(timezone: "Africa/Casablanca")
    TimeZone.create(timezone: "Africa/Monrovia")
    TimeZone.create(timezone: "Africa/Algiers")
    TimeZone.create(timezone: "Africa/Cairo")
    TimeZone.create(timezone: "Africa/Nairobi")
    TimeZone.create(timezone: "Etc/UTC")

    TimeZone.create(timezone: "Asia/Kabul")
    TimeZone.create(timezone: "Asia/Karachi")
    TimeZone.create(timezone: "Asia/Kuwait")
    TimeZone.create(timezone: "Asia/Riyadh")
    TimeZone.create(timezone: "Asia/Baghdad")
    TimeZone.create(timezone: "Asia/Baku")
    TimeZone.create(timezone: "Asia/Almaty")
    TimeZone.create(timezone: "Asia/Novosibirsk")
    TimeZone.create(timezone: "Asia/Rangoon")
    TimeZone.create(timezone: "Asia/Bangkok")
    TimeZone.create(timezone: "Asia/Jakarta")
    TimeZone.create(timezone: "Asia/Krasnoyarsk")
    TimeZone.create(timezone: "Asia/Shanghai")
    TimeZone.create(timezone: "Asia/Chongqing")
    TimeZone.create(timezone: "Asia/Hong_kong")
    TimeZone.create(timezone: "Asia/Ulaanbaatar")
    TimeZone.create(timezone: "Asia/Seoul")
    TimeZone.create(timezone: "Asia/Tokyo")
    TimeZone.create(timezone: "Asia/Urumqi")
    TimeZone.create(timezone: "Asia/Kuala_Lumpur")
    TimeZone.create(timezone: "Asia/Singapore")
    TimeZone.create(timezone: "Asia/Taipei")
    TimeZone.create(timezone: "Asia/Irkutsk")
    TimeZone.create(timezone: "Asia/Colombo")
    TimeZone.create(timezone: "Asia/Kamchatka")
    TimeZone.create(timezone: "Asia/Dhaka")
    TimeZone.create(timezone: "Asia/Kathmandu")
    TimeZone.create(timezone: "Asia/Kolkata")
    TimeZone.create(timezone: "Asia/Tashkent")
    TimeZone.create(timezone: "Asia/Tehran")
    TimeZone.create(timezone: "Asia/Magadan")
    TimeZone.create(timezone: "Asia/Tbilisi")
    TimeZone.create(timezone: "Asia/Muscat")
    TimeZone.create(timezone: "Asia/Vladivostok")
    TimeZone.create(timezone: "Asia/Yakutsk")
    TimeZone.create(timezone: "Asia/Yekaterinburg")
    TimeZone.create(timezone: "Asia/Yerevan")
   
    TimeZone.create(timezone: "Australia/Darwin")
    TimeZone.create(timezone: "Australia/Adelaide")
    TimeZone.create(timezone: "Australia/Melbourne")
    TimeZone.create(timezone: "Australia/Perth")
    TimeZone.create(timezone: "Australia/Sydney")
    TimeZone.create(timezone: "Australia/Brisbane")
    TimeZone.create(timezone: "Australia/Hobart")

    TimeZone.create(timezone: "Pacific/Guam")
    TimeZone.create(timezone: "Pacific/Port_Moresby")
    TimeZone.create(timezone: "Pacific/Guadalcanal")
    TimeZone.create(timezone: "Pacific/Noumea")
    TimeZone.create(timezone: "Pacific/Fiji")
    TimeZone.create(timezone: "Pacific/Majuro")
    TimeZone.create(timezone: "Pacific/Auckland")
    TimeZone.create(timezone: "Pacific/Tongatapu")
    TimeZone.create(timezone: "Pacific/Fakaofo")
    TimeZone.create(timezone: "Pacific/Chatham")
    TimeZone.create(timezone: "Pacific/Apia")

  end
end
