require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EarlyVenuesController do

  # This should return the minimal set of attributes required to create a valid
  # EarlyVenue. As you add validations to EarlyVenue, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "username," => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EarlyVenuesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all early_venues as @early_venues" do
      early_venue = EarlyVenue.create! valid_attributes
      get :index, {}, valid_session
      assigns(:early_venues).should eq([early_venue])
    end
  end

  describe "GET show" do
    it "assigns the requested early_venue as @early_venue" do
      early_venue = EarlyVenue.create! valid_attributes
      get :show, {:id => early_venue.to_param}, valid_session
      assigns(:early_venue).should eq(early_venue)
    end
  end

  describe "GET new" do
    it "assigns a new early_venue as @early_venue" do
      get :new, {}, valid_session
      assigns(:early_venue).should be_a_new(EarlyVenue)
    end
  end

  describe "GET edit" do
    it "assigns the requested early_venue as @early_venue" do
      early_venue = EarlyVenue.create! valid_attributes
      get :edit, {:id => early_venue.to_param}, valid_session
      assigns(:early_venue).should eq(early_venue)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EarlyVenue" do
        expect {
          post :create, {:early_venue => valid_attributes}, valid_session
        }.to change(EarlyVenue, :count).by(1)
      end

      it "assigns a newly created early_venue as @early_venue" do
        post :create, {:early_venue => valid_attributes}, valid_session
        assigns(:early_venue).should be_a(EarlyVenue)
        assigns(:early_venue).should be_persisted
      end

      it "redirects to the created early_venue" do
        post :create, {:early_venue => valid_attributes}, valid_session
        response.should redirect_to(EarlyVenue.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved early_venue as @early_venue" do
        # Trigger the behavior that occurs when invalid params are submitted
        EarlyVenue.any_instance.stub(:save).and_return(false)
        post :create, {:early_venue => { "username," => "invalid value" }}, valid_session
        assigns(:early_venue).should be_a_new(EarlyVenue)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EarlyVenue.any_instance.stub(:save).and_return(false)
        post :create, {:early_venue => { "username," => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested early_venue" do
        early_venue = EarlyVenue.create! valid_attributes
        # Assuming there are no other early_venues in the database, this
        # specifies that the EarlyVenue created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EarlyVenue.any_instance.should_receive(:update).with({ "username," => "MyString" })
        put :update, {:id => early_venue.to_param, :early_venue => { "username," => "MyString" }}, valid_session
      end

      it "assigns the requested early_venue as @early_venue" do
        early_venue = EarlyVenue.create! valid_attributes
        put :update, {:id => early_venue.to_param, :early_venue => valid_attributes}, valid_session
        assigns(:early_venue).should eq(early_venue)
      end

      it "redirects to the early_venue" do
        early_venue = EarlyVenue.create! valid_attributes
        put :update, {:id => early_venue.to_param, :early_venue => valid_attributes}, valid_session
        response.should redirect_to(early_venue)
      end
    end

    describe "with invalid params" do
      it "assigns the early_venue as @early_venue" do
        early_venue = EarlyVenue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EarlyVenue.any_instance.stub(:save).and_return(false)
        put :update, {:id => early_venue.to_param, :early_venue => { "username," => "invalid value" }}, valid_session
        assigns(:early_venue).should eq(early_venue)
      end

      it "re-renders the 'edit' template" do
        early_venue = EarlyVenue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EarlyVenue.any_instance.stub(:save).and_return(false)
        put :update, {:id => early_venue.to_param, :early_venue => { "username," => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested early_venue" do
      early_venue = EarlyVenue.create! valid_attributes
      expect {
        delete :destroy, {:id => early_venue.to_param}, valid_session
      }.to change(EarlyVenue, :count).by(-1)
    end

    it "redirects to the early_venues list" do
      early_venue = EarlyVenue.create! valid_attributes
      delete :destroy, {:id => early_venue.to_param}, valid_session
      response.should redirect_to(early_venues_url)
    end
  end

end
