class AdminUser < ActiveRecord::Base
  # This is for seeing the raw data in the backend of the live website
  # Not sure if this is the best route to go, wanted something autogenerated
  # Probably better to write a custom backend for Admins

  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end
